name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: python -m coverage run -m pytest

      - name: Print Test Results
        run: python -m coverage report -m

      - name: Run Mutation Tests
        run: python -m mutmut run
